#+TITLE: Doom Emacs Config
#+PROPERTY: header-args:emacs-lisp :tangle config.el :results none
* Table of Contents :toc:
- [[#about-this-config][About this config]]
- [[#personal-info][Personal Info]]
  - [[#name-and-email][Name and email]]
  - [[#projects-locations][Projects locations]]
  - [[#org-files-location][Org files location]]
- [[#personal-preferences][Personal preferences]]
  - [[#highlighted-menu][Highlighted menu]]
  - [[#splash-image][Splash image]]
  - [[#footer][Footer]]
  - [[#theme][Theme]]
  - [[#fonts][Fonts]]
  - [[#comments][Comments]]
  - [[#popup-text][Popup text]]
  - [[#modeline][Modeline]]
  - [[#beacon-mode][Beacon mode]]
  - [[#minimap][Minimap]]
  - [[#line-numbers][Line numbers]]
  - [[#starting-window-dimension][Starting window dimension]]
  - [[#transparency][Transparency]]
  - [[#window-decorators][Window decorators]]
  - [[#warnings-level][Warnings level]]
  - [[#google-translator][Google translator]]
- [[#forge-pull-requests][Forge Pull Requests]]
- [[#version-control-systems][Version control systems]]
  - [[#git][Git]]
- [[#editing-configuration][Editing configuration]]
  - [[#key-chords][Key chords]]
  - [[#search][Search]]
- [[#org][Org]]
  - [[#preferences][Preferences]]
  - [[#svg-tag-mode][Svg-Tag-Mode]]
  - [[#org-modern][Org-modern]]
  - [[#org-appear][Org-appear]]
  - [[#org-journal][Org-Journal]]
  - [[#org-roam][Org-Roam]]
  - [[#beautify-markdown-on-emacs][Beautify Markdown on Emacs]]
  - [[#toc-org][TOC Org]]
- [[#ai][AI]]
  - [[#claude-code][Claude Code]]
  - [[#openai-codex][OpenAI Codex]]
  - [[#tree-sitter-and-colors][Tree sitter and colors]]

* About this config
This configuration works with Emacs 30+, you'll need to install Doom Emacs.

You do not need to run 'doom sync' after modifying this file!

Before that you need M-x org-babel-tangle so this writes all emacs-lisp blocks to config.el after generating the config.el file, this will sync and reload Doom with doom sync.

The following will generate the config.el, reload doom to restart emacs and print a status message.

Just save config.org it tangles to config.el immediately calls doom/reload so changes take effect without restarting Emacs.

Note: sometimes you need to
C-c C-c on the top of the org file. It updates the local config of the file.
#+begin_src emacs-lisp
(defun my/org-babel-tangle-and-reload ()
  "Auto-tangle config.org, reload Doom, and notify."
  (when (string-equal (file-truename (buffer-file-name))
                    (file-truename (expand-file-name "config.org" doom-user-dir)))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle)
      (condition-case err
          (progn
            (doom/reload)
            (message "Doom reloaded after tangling config.org at %s" (current-time-string)))
        (error
         (message "Reload failed: %s" (error-message-string err)))))))

(add-hook 'org-mode-hook
          (lambda ()
            (when (string-equal (buffer-file-name)
                                (expand-file-name "config.org" doom-user-dir))
              (add-hook 'after-save-hook #'my/org-babel-tangle-and-reload nil 'local))))
#+end_src

* Personal Info
** Name and email
Set my name and email.
#+begin_src emacs-lisp
(setq user-full-name "Alan M."
      user-mail-address "alan.maciel.salcedo@gmail.com")
#+end_src

** Projects locations
MOST IMPORTANT CONFIG - Set your project folders.
#+begin_src emacs-lisp
(setq projectile-project-search-path '("~/Projects" "~/Labs"))
#+end_src

** Org files location
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!.
#+begin_src emacs-lisp
(after! org
  (setq org-directory "~/org/")
  (setq org-agenda-files '("~/org/agenda.org"))
  (setq org-log-done 'note )
  )
#+end_src

* Personal preferences
** Highlighted menu
Like in the vt100s ttys

#+begin_src emacs-lisp
;; Enable line highlight only in dashboard
;; (add-hook '+doom-dashboard-mode-hook #'hl-line-mode)
;; Dashboard: make keyboard selection look like mouse hover
;; Yellow bg + black text only on Doom dashboard, via overlay
#+end_src

** Splash image
Set splash image.

#+begin_src emacs-lisp
;; (setq fancy-splash-image "~/dotfiles-local/emacs/doom.d/splash/lucky-doom-emacs-color.png")
#+end_src

Remove splash image.
#+begin_src emacs-lisp
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-banner)
#+end_src

** Footer
Remove footer.
#+begin_src emacs-lisp
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-footer)
#+end_src

** Theme
Select the colors you like.
#+begin_src emacs-lisp
(setq doom-theme 'doom-monokai-octagon
      doom-themes-treemacs-enable-variable-pitch nil)
#+end_src

*** Custom themes
If you want to load a custom theme.
#+begin_src emacs-lisp
;; (add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
;; (load-theme 'twilight t)
;; (setq doom-theme 'twilight)
#+end_src

*** Circadian themes
Change themes depending the time of the day.
#+begin_src emacs-lisp
#+end_src

** Fonts
My recommendation is JetBrains Mono. Use M-x reload-user-settings to see the font change.

Some cool fonts:
"CaskaydiaCove Nerd Font Mono"
"Iosevka Term"
"JetBrains Mono"
"Overpass"
"IBM Plex Mono"

To install fonts in MacOS

brew install fontconfig

brew install --cask \
font-jetbrains-mono-nerd-font \
font-caskaydia-cove-nerd-font \
font-iosevka-term-nerd-font \
font-fira-mono-nerd-font \
font-blex-mono-nerd-font \
font-overpass-mono-nerd-font

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Iosevka Nerd Font" :size 20 )
      doom-big-font (font-spec :family "Iosevka Nerd Font" :size 24)
      doom-variable-pitch-font (font-spec :family "Overpass Nerd Font" :size 22)
      doom-serif-font (font-spec :family "BlexMono Nerd Font" :weight 'light :size 22))
#+end_src

** Comments
I like to see comments in italics.
#+begin_src emacs-lisp
(custom-set-faces!
  '(font-lock-comment-face :slant italic))
#+end_src

** Popup text
Automatic documentation popup while autocompleting is nice, but let’s reduce the font size a little bit so that it doesn’t cover the screen too much and makes it easier to skim for information.
#+begin_src emacs-lisp
(custom-set-faces! '((corfu-popupinfo) :height 0.9))
#+end_src

** Modeline
Make modeline thicker and add an orange accent.
#+begin_src emacs-lisp
(use-package! doom-modeline
  :config
  (setq doom-modeline-persp-name t))

(custom-set-faces!
  '(doom-modeline-buffer-modified :foreground "orange"))
#+end_src

*** Height
Some tweaks to doom-modeline.
#+begin_src emacs-lisp
(setq doom-modeline-height 30)
#+end_src

*** Hide default encoding
#+begin_src emacs-lisp
(defun doom-modeline-conditional-buffer-encoding ()
  "We expect the encoding to be LF UTF-8, so only show the modeline when this is not the case"
  (setq-local doom-modeline-buffer-encoding
              (unless (and (memq (plist-get (coding-system-plist buffer-file-coding-system) :category)
                                 '(coding-category-undecided coding-category-utf-8))
                           (not (memq (coding-system-eol-type buffer-file-coding-system) '(1 2))))
                t)))

(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)
#+end_src

*** Keycast
#+begin_src emacs-lisp
(use-package! keycast
  :commands keycast-mode
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line."
    :global t
    (if keycast-mode
        (progn
          (add-hook 'pre-command-hook 'keycast--update t)
          (add-to-list 'global-mode-string '("" mode-line-keycast " ")))
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (remove '("" mode-line-keycast " ") global-mode-string))))
  (custom-set-faces!
    '(keycast-command :inherit doom-modeline-debug
                      :height 0.9)
    '(keycast-key :inherit custom-modified
                  :height 1.1
                  :weight bold)))
#+end_src

** Beacon mode
Highlight the current line when moving.
#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src

** Minimap
If you like this type of things.
#+begin_src emacs-lisp
(setq minimap-window-location 'right)
(map! :leader
      (:prefix ("t" . "toggle")
       :desc "Toggle minimap-mode" "M" #'minimap-mode))
#+end_src

** Line numbers
How do you want to display line numbers? t, nil, or relative?.
#+begin_src emacs-lisp
  (setq display-line-numbers-type t)
#+end_src

** Starting window dimension
Start the initial frame not maximized.
#+begin_src emacs-lisp
(setq default-frame-alist '((width . 115)(height . 34)))
#+end_src

** Transparency
#+begin_src emacs-lisp
;; (add-to-list 'default-frame-alist '(alpha . 90))
#+end_src

** Window decorators
The title bar will have the same color as the window.
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
(add-to-list 'default-frame-alist '(ns-appearance . dark))
#+end_src

Change the window title to something more simple
#+begin_src emacs-lisp
#+end_src

** Warnings level
Stop some boring warnings
#+begin_src emacs-lisp
(setq warning-minimum-level :emergency)
#+end_src


** Google translator
Google Traductor, source and target languages
#+begin_src emacs-lisp
(setq google-translate-default-source-language "en")
(setq google-translate-default-target-language "es-MX")
#+end_src

* Forge Pull Requests
Handle Github Pull Requests without leaving Doom Emacs.

#+begin_src emacs-lisp
;; Always use dwim:origin so Forge follows the branch’s upstream if set,
;; else defaults to "origin"
(setq forge-remote "dwim:origin")
;; (setq forge-remote "origin")
;; Pull only recent topics by default (1 month back)
(setq forge-pull-limit
      (time-subtract (current-time)
                     (days-to-time 30)))  ;; 30 days

(setq forge-topic-list-limit 50          ;; máximo global
      forge-topic-list-limit-per-repo 50) ;; máximo por repo

#+end_src


* Version control systems
** Git
*** Git gutter
The diff changes are reflected in the left fringe. However, I find them to be a little bit too intrusive, so let’s change how they looks by blending the colors into the background a little bit.
#+begin_src emacs-lisp
(use-package! diff-hl
  :config
  (custom-set-faces!
    `((diff-hl-change)
      :foreground ,(doom-blend (doom-color 'bg) (doom-color 'blue) 0.5))
    `((diff-hl-insert)
      :foreground ,(doom-blend (doom-color 'bg) (doom-color 'green) 0.5)))
)
#+end_src

*** Magit
Start projectile with magit, uncomment below:
#+begin_src emacs-lisp
(after! projectile
  (defun open-projectile-with-magit (&optional DIRECTORY CACHE)
    (interactive)
    (magit-status DIRECTORY)
    (if (fboundp 'magit-fetch-from-upstream)
        (call-interactively #'magit-fetch-from-upstream)
      (call-interactively #'magit-fetch-current)))
  (setq +workspaces-switch-project-function #'open-projectile-with-magit))
#+end_src


* Editing configuration

** Key chords
Using chords fd or jh in the homerow instead of trying to reach esc everytime.
#+begin_src emacs-lisp
(require 'key-chord)
(key-chord-mode t)
;; (key-chord-define-global "ue" 'evil-normal-state) ;; in DVORAK
;; (key-chord-define-global "UE" 'evil-normal-state) ;; in DVORAK
(key-chord-define-global "fd" 'evil-normal-state) ;; in QWERTY
(key-chord-define-global "FD" 'evil-normal-state) ;; in QWERTY
#+end_src

** Search
*** Ignore folders
#+begin_src emacs-lisp
(after! projectile
  (setq projectile-globally-ignored-directories '("flow-typed" "node_modules" "~/.config/emacs/.local/" ".idea" ".vscode" ".ensime_cache" ".eunit" ".git" ".hg" ".fslckout" "_FOSSIL_" ".bzr" "_darcs" ".tox" ".svn" ".stack-work" ".ccls-cache" ".cache" ".clangd")))
#+end_src


* Org
** Preferences
*** Custom faces
#+begin_src emacs-lisp
(after! org
  ;; Set some faces
  (custom-set-faces!
    `((org-quote)
      :foreground ,(doom-color 'blue) :extend t)
    `((org-block-begin-line org-block-end-line)
      :background ,(doom-color 'bg)))
  ;; Change how LaTeX and image previews are shown
  (setq org-highlight-latex-and-related '(native entities script)
        org-image-actual-width (min (/ (display-pixel-width) 3) 800)))
#+end_src

Emacs version 29 can now tell the difference between ‘regular’ or ’normal’ font weights and ‘medium’ weights. Let’s use the medium weights for org-mode headings.

#+begin_src emacs-lisp
(after! org
  (custom-set-faces!
    `((org-document-title)
      :foreground ,(face-attribute 'org-document-title :foreground)
      :height 1.3 :weight bold)
    `((org-level-1)
      :foreground ,(face-attribute 'outline-1 :foreground)
      :height 1.1 :weight medium)
    `((org-level-2)
      :foreground ,(face-attribute 'outline-2 :foreground)
      :weight medium)
    `((org-level-3)
      :foreground ,(face-attribute 'outline-3 :foreground)
      :weight medium)
    `((org-level-4)
      :foreground ,(face-attribute 'outline-4 :foreground)
      :weight medium)
    `((org-level-5)
      :foreground ,(face-attribute 'outline-5 :foreground)
      :weight medium)))
#+end_src

*** Pretty bullets
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-indent-mode)
(use-package! org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

*** Current line
Turn off highlighting current line, highlight mode is nice. However, in an Org-mode buffer, I feel like it might be too much. Let’s turn off hl-line-mode in text buffers for now.
#+begin_src emacs-lisp
(add-hook 'text-mode-hook (lambda () (hl-line-mode -1)))
#+end_src

** Svg-Tag-Mode
The configurations for svg-tag-mode go here, too:
#+begin_src emacs-lisp
(use-package! svg-tag-mode
  :config
  (defconst date-re "[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}")
  (defconst time-re "[0-9]\\{2\\}:[0-9]\\{2\\}")
  (defconst day-re "[A-Za-z]\\{3\\}")
  (defconst day-time-re (format "\\(%s\\)? ?\\(%s\\)?" day-re time-re))

  (defun svg-progress-percent (value)
    (svg-image (svg-lib-concat
                (svg-lib-progress-bar
                 (/ (string-to-number value) 100.0) nil
                 :height 0.8 :foreground (doom-color 'fg) :background (doom-color 'bg)
                 :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
                (svg-lib-tag (concat value "%") nil
                             :height 0.8 :foreground (doom-color 'fg) :background (doom-color 'bg)
                             :stroke 0 :margin 0)) :ascent 'center))

  (defun svg-progress-count (value)
    (let* ((seq (mapcar #'string-to-number (split-string value "/")))
           (count (float (car seq)))
           (total (float (cadr seq))))
      (svg-image (svg-lib-concat
                  (svg-lib-progress-bar (/ count total) nil
                                        :foreground (doom-color 'fg)
                                        :background (doom-color 'bg) :height 0.8
                                        :margin 0 :stroke 2 :radius 3 :padding 2 :width 11)
                  (svg-lib-tag value nil
                               :foreground (doom-color 'fg)
                               :background (doom-color 'bg)
                               :stroke 0 :margin 0 :height 0.8)) :ascent 'center)))

  (set-face-attribute 'svg-tag-default-face nil :family "Alegreya Sans")
  (setq svg-tag-tags
        `(;; Progress e.g. [63%] or [10/15]
          ("\\(\\[[0-9]\\{1,3\\}%\\]\\)" . ((lambda (tag)
                                            (svg-progress-percent (substring tag 1 -2)))))
          ("\\(\\[[0-9]+/[0-9]+\\]\\)" . ((lambda (tag)
                                            (svg-progress-count (substring tag 1 -1)))))
          ;; Task priority e.g. [#A], [#B], or [#C]
          ("\\[#A\\]" . ((lambda (tag) (svg-tag-make tag :face 'error :inverse t :height .85
                                                     :beg 2 :end -1 :margin 0 :radius 10))))
          ("\\[#B\\]" . ((lambda (tag) (svg-tag-make tag :face 'warning :inverse t :height .85
                                                     :beg 2 :end -1 :margin 0 :radius 10))))
          ("\\[#C\\]" . ((lambda (tag) (svg-tag-make tag :face 'org-todo :inverse t :height .85
                                                     :beg 2 :end -1 :margin 0 :radius 10))))
          ;; Keywords
          ("TODO" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face 'org-todo))))
          ("HOLD" . ((lambda (tag) (svg-tag-make tag :height .85 :face 'org-todo))))
          ("DONE\\|STOP" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face 'org-done))))
          ("NEXT\\|WAIT" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face '+org-todo-active))))
          ("REPEAT\\|EVENT\\|PROJ\\|IDEA" .
           ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face '+org-todo-project))))
          ("REVIEW" . ((lambda (tag) (svg-tag-make tag :inverse t :height .85 :face '+org-todo-onhold))))))
  :hook (org-mode . svg-tag-mode)
)

(setq svg-tag-tags
      '((":TODO:" . ((lambda (tag) (svg-tag-make "TODO"))))))
(setq svg-tag-tags
      '((":HELLO:" .  ((lambda (tag) (svg-tag-make "HELLO"))
                       (lambda () (interactive) (message "Hello world!"))
                       "Print a greeting message"))))
(setq svg-tag-tags
      '((":TODO:" . ((lambda (tag) (svg-tag-make tag))))))
(setq svg-tag-tags
      '(("\\(:[A-Z]+:\\)" . ((lambda (tag)
                               (svg-tag-make tag :beg 1 :end -1))))))
(setq svg-tag-tags
      '(("\\(:[A-Z]+\\)\\|[a-zA-Z#0-9]+:" . ((lambda (tag)
                                              (svg-tag-make tag :beg 1 :inverse t
                                                            :margin 0 :crop-right t))))
        (":[A-Z]+\\(\\|[a-zA-Z#0-9]+:\\)" . ((lambda (tag)
                                              (svg-tag-make tag :beg 1 :end -1
                                                            :margin 0 :crop-left t))))))
(setq svg-tag-tags
      '(("\\(:#[A-Za-z0-9]+\\)" . ((lambda (tag)
                                     (svg-tag-make tag :beg 2))))
        ("\\(:#[A-Za-z0-9]+:\\)$" . ((lambda (tag)
                                       (svg-tag-make tag :beg 2 :end -1))))))
#+end_src

*** Fix render in agenda
#+begin_src emacs-lisp
  (defun org-agenda-show-svg ()
    (let* ((case-fold-search nil)
           (keywords (mapcar #'svg-tag--build-keywords svg-tag--active-tags))
           (keyword (car keywords)))
      (while keyword
        (save-excursion
          (while (re-search-forward (nth 0 keyword) nil t)
            (overlay-put (make-overlay
                          (match-beginning 0) (match-end 0))
                         'display  (nth 3 (eval (nth 2 keyword)))) ))
        (pop keywords)
        (setq keyword (car keywords)))))
  (add-hook 'org-agenda-finalize-hook #'org-agenda-show-svg)
#+end_src

** Org-modern
org-modern is really cool – especially when combined with svg-tag-mode. The only downside is it doesn’t play well with org-indent-mode (for now).
#+begin_src emacs-lisp
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq
   ;; Edit settings
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t
   ;; Appearance
   org-modern-radio-target    '("❰" t "❱")
   org-modern-internal-target '("↪ " t "")
   org-modern-todo nil
   org-modern-tag nil
   org-modern-timestamp t
   org-modern-statistics nil
   org-modern-progress nil
   org-modern-priority nil
   org-modern-horizontal-rule "──────────"
   org-modern-hide-stars "·"
   org-modern-star ["⁖"]
   org-modern-keyword "‣"
   org-modern-list '((43 . "•")
                     (45 . "–")
                     (42 . "↪")))
  (custom-set-faces!
    `((org-modern-tag)
      :background ,(doom-blend (doom-color 'blue) (doom-color 'bg) 0.1)
      :foreground ,(doom-color 'grey))
    `((org-modern-radio-target org-modern-internal-target)
      :inherit 'default :foreground ,(doom-color 'blue)))
  )
#+end_src

** Org-appear
org-appear for seemless look:
#+begin_src emacs-lisp
;; (use-package! org-appear
;;   :hook
;;   (org-mode . org-appear-mode)
;;   :config
;;   (setq org-hide-emphasis-markers t
;;         org-appear-autolinks 'just-brackets))
#+end_src

** Org-Journal
Set the name and the date format:
#+begin_src emacs-lisp
(setq org-journal-date-prefix "#+TITLE: "
 org-journal-time-prefix "* "
 org-journal-date-format "%a, %Y-%m-%d"
 org-journal-file-format "%Y-%m-%d.org")

#+end_src

** Org-Roam
*** Document everything, make a second brain.
#+begin_src emacs-lisp
(use-package! org-roam
  :custom
  (org-roam-directory (file-truename "~/roam"))
  :config
  (setq org-roam-node-display-template
        (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-db-autosync-mode)
  (require 'org-roam-protocol))

(after! org-agenda
  (require 'org-super-agenda)
  (org-super-agenda-mode)
  (setq org-agenda-custom-commands
        '(("o" "Overview"
           ((alltodo ""
                     ((org-super-agenda-groups
                       '((:name "Today" :scheduled today)
                         (:name "Overdue" :deadline past)
                         (:name "Due Soon" :deadline future)
                         (:name "Important" :priority "A"))))))))))

(after! org-roam
  (map!
   ;; Org-roam core
   "C-c n l" #'org-roam-buffer-toggle
   "C-c n f" #'org-roam-node-find
   "C-c n g" #'org-roam-graph
   "C-c n i" #'org-roam-node-insert
   "C-c n c" #'org-roam-capture
   ;; Dailies
   "C-c n j" #'org-roam-dailies-capture-today
   ;; Completion
   "C-M-i"   #'completion-at-point))

#+end_src
*** Files location and Window title
#+begin_src emacs-lisp
(setq frame-title-format
      '(""
        (:eval
         (let ((bf (or buffer-file-name "")))
           (if (or (and (bound-and-true-p org-roam-directory)
                        (string-match-p
                         (regexp-quote (file-truename (expand-file-name org-roam-directory)))
                         (file-truename bf)))
                   (string-match-p
                    (regexp-quote (file-truename "~/RoamNotes"))
                    (file-truename bf)))
               (replace-regexp-in-string
                ".*/[0-9]*-?" "☰ "
                (subst-char-in-string ?_ ?\s bf))
             "%b")))
        (:eval
         (when-let ((project-name (and (featurep 'projectile) (projectile-project-name))))
           (unless (string= "-" project-name)
             (format (if (buffer-modified-p) " ◉ %s" "  ●  %s") project-name))))))
#+end_src


*** Websocket
#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)
#+end_src

*** Org-Roam UI
#+begin_src emacs-lisp
(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;; :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))

(add-to-list 'display-buffer-alist
             '("\\*org-roam\\*"
               (display-buffer-in-side-window)
               (side . right)
               (slot . 0)
               (window-width . 0.33)
               (window-parameters . ((no-other-window . t)
                                     (no-delete-other-windows . t)))))
#+end_src

** Beautify Markdown on Emacs
I know org-mode is more complete than markdown, but I don't need all the features of org-mode, so I prefer to use markdown.

Custom faces for headers, hide/show markup on cursor line, tables, emojis.
#+begin_src emacs-lisp
;; Markdown beautification
(after! markdown-mode
  ;; setq-default es necesario porque markdown-mode usa make-variable-buffer-local,
  ;; lo que hace que setq solo afecte el buffer actual, no todos los futuros buffers
  (setq-default markdown-fontify-whole-heading-line nil)
  (setq-default markdown-hide-markup               t)
  (setq-default markdown-hide-urls                 t)

  ;; --- Warm reading theme para markdown ---
  ;; Paleta: fondo crema cálido, texto marrón chocolate, headings marrón oscuro
  (custom-set-faces!
    ;; Links
    '(markdown-link-face           :foreground "#2A6496" :underline t)
    '(markdown-url-face            :foreground "#8B7B6B" :height 0.85)
    ;; Strikethrough
    '(markdown-strike-through-face :height 1.0 :strike-through t :weight normal :slant normal)
    ;; Bold/Italic
    '(markdown-bold-face           :foreground "#4A3322" :weight bold)
    '(markdown-italic-face         :foreground "#4A3728" :slant italic)
    ;; Code inline — fondo más marcado para distinguir del texto
    '(markdown-inline-code-face    :foreground "#5C3D2E" :background "#2e313d" :family "Iosevka Nerd Font" :weight light :height 140)
    ;; Code blocks — fondo claramente distinto del fondo de página
    '(markdown-pre-face            :foreground "#5C4A3A" :background "#2e313d" :extend t :family "Iosevka Nerd Font" :weight light :height 140)
    '(markdown-code-face           :foreground "#5C4A3A" :background "#2e313d" :extend t :family "Iosevka Nerd Font" :weight light :height 140)
    ;; Headers — todos marrón oscuro, solo varía el tamaño
    '(markdown-header-delimiter-face :foreground "#8B7B6B" :height 0.9)
    '(markdown-header-face-1 :height 1.6  :foreground "#3E2B1E" :weight extra-bold :inherit markdown-header-face)
    '(markdown-header-face-2 :height 1.4  :foreground "#3E2B1E" :weight extra-bold :inherit markdown-header-face)
    '(markdown-header-face-3 :height 1.2  :foreground "#3E2B1E" :weight extra-bold :inherit markdown-header-face)
    '(markdown-header-face-4 :height 1.15 :foreground "#3E2B1E" :weight bold       :inherit markdown-header-face)
    '(markdown-header-face-5 :height 1.1  :foreground "#5A4636" :weight bold       :inherit markdown-header-face)
    '(markdown-header-face-6 :height 1.05 :foreground "#6B5744" :weight semi-bold  :inherit markdown-header-face)
    ;; Blockquotes — texto normal (no italic), fondo lavanda claro
    '(markdown-blockquote-face     :foreground "#4A3728" :slant normal :background "#EDE7DC" :extend t)
    ;; HR — línea dorada/ocre
    '(markdown-hr-face             :foreground "#C4A265" :strike-through "#C4A265")
    ;; Lista
    '(markdown-list-face           :foreground "#4A3728"))

  ;; Fondo crema + fuente serif para prosa (solo en buffers markdown)
  (defun nb/markdown-warm-theme ()
    "Aplica tema warm reading al buffer markdown."
    ;; Fondo crema cálido
    (face-remap-add-relative 'default
      :background "#F3EDE4" :foreground "#4A3728" :family "Charter" :height 150)
    ;; Fringe sigue el fondo
    (face-remap-add-relative 'fringe :background "#F3EDE4")
    ;; Line numbers sutiles
    (face-remap-add-relative 'line-number :foreground "#C4B8A8" :background "#F3EDE4")
    (face-remap-add-relative 'line-number-current-line :foreground "#8B7B6B" :background "#F3EDE4")
    ;; Region/selección cálida
    (face-remap-add-relative 'region :background "#DDD4C4")
    ;; Cursor azul acero (evil sobreescribe face, hay que usar sus variables)
    (face-remap-add-relative 'cursor :background "#2A6496")
    (setq-local evil-normal-state-cursor '(box "#2A6496"))
    (setq-local evil-insert-state-cursor '(bar "#2A6496"))
    (setq-local evil-visual-state-cursor '(hollow "#2A6496"))
    ;; Sin números de línea
    (display-line-numbers-mode -1))

  (add-hook 'markdown-mode-hook #'nb/markdown-warm-theme)
  (add-hook 'markdown-mode-hook #'abbrev-mode)

  ;; --- Olivetti: texto centrado, ancho cómodo para lectura ---
  (require 'olivetti)
  (defun nb/markdown-olivetti ()
    "Activa olivetti para centrar el texto markdown."
    (olivetti-mode 1)
    (olivetti-set-width 82))
  (add-hook 'markdown-mode-hook #'nb/markdown-olivetti)

  ;; --- Revelar markup en la línea actual (### ** etc.) ---
  (defvar-local nb/markdown-shown-line-beg nil
    "Posición de inicio de la línea que actualmente muestra el markup crudo.")

  (defun nb/on-table-line-p ()
    "Non-nil si la línea actual es una fila de tabla markdown."
    (save-excursion
      (beginning-of-line)
      (looking-at "[[:space:]]*|")))

  (defun nb/refontify-line (line-beg)
    "Re-aplica font-lock a la línea que empieza en LINE-BEG para volver a ocultar el markup."
    (when (and line-beg
               (integer-or-marker-p line-beg)
               (>= line-beg (point-min))
               (<= line-beg (point-max)))
      (save-excursion
        (goto-char line-beg)
        (font-lock-fontify-region (line-beginning-position)
                                  (line-end-position)))))

  (defun nb/unhide-current-line ()
    "Muestra el markup markdown en la línea actual; lo vuelve a ocultar al moverse.
Ignora líneas de tabla — valign maneja su display."
    (unless (minibufferp)
      (let ((cur-beg (line-beginning-position)))
        (unless (equal cur-beg nb/markdown-shown-line-beg)
          ;; Vuelve a ocultar la línea anterior
          (nb/refontify-line nb/markdown-shown-line-beg)
          ;; En líneas de tabla, no tocar nada (valign usa display properties)
          (if (nb/on-table-line-p)
              (setq nb/markdown-shown-line-beg nil)
            ;; En otras líneas, revelar el markup
            (with-silent-modifications
              (remove-text-properties cur-beg (line-end-position)
                                      '(invisible nil display nil composition nil)))
            (setq nb/markdown-shown-line-beg cur-beg))))))

  (defun nb/markdown-setup ()
    "Setup por buffer para markdown."
    (setq-local nb/markdown-shown-line-beg nil)
    (add-hook 'post-command-hook #'nb/unhide-current-line nil t))

  (add-hook 'markdown-mode-hook #'nb/markdown-setup)

  ;; --- Background sutil en regiones de tabla ---
  (defvar-local nb/table-overlays nil "Overlays para fondo de tabla.")
  (defvar-local nb/table-update-timer nil "Timer debounce para actualizar overlays.")

  (defun nb/update-table-overlays ()
    "Agrega background sutil a regiones de tabla markdown."
    (when (timerp nb/table-update-timer)
      (cancel-timer nb/table-update-timer)
      (setq nb/table-update-timer nil))
    (mapc #'delete-overlay nb/table-overlays)
    (setq nb/table-overlays nil)
    (let ((bg-alt "#EDE8DD")) ;; tabla: crema ligeramente más cálido que el fondo
      (save-excursion
        (goto-char (point-min))
        (while (re-search-forward "^[[:space:]]*|" nil t)
          (beginning-of-line)
          (let ((beg (point)))
            (while (and (not (eobp))
                        (looking-at "^[[:space:]]*|"))
              (forward-line 1))
            (let ((ov (make-overlay beg (point) nil t nil)))
              (overlay-put ov 'face `(:background ,bg-alt :extend t))
              (overlay-put ov 'evaporate t)
              (overlay-put ov 'nb-table t)
              (push ov nb/table-overlays)))))))

  (defun nb/schedule-table-overlay-update (&rest _)
    "Actualiza overlays de tabla con debounce."
    (when (timerp nb/table-update-timer)
      (cancel-timer nb/table-update-timer))
    (setq nb/table-update-timer
          (run-with-idle-timer 0.5 nil
            (lambda (buf)
              (when (buffer-live-p buf)
                (with-current-buffer buf
                  (nb/update-table-overlays))))
            (current-buffer))))

  (defun nb/table-bg-setup ()
    "Inicializa overlays de fondo para tablas."
    (nb/update-table-overlays)
    (add-hook 'after-change-functions #'nb/schedule-table-overlay-update nil t))

  (add-hook 'markdown-mode-hook #'nb/table-bg-setup)

  ;; --- Valign: tablas pixel-perfect con fancy bars ---
  (require 'valign)
  (setq valign-fancy-bar t)

  (defun nb/valign-setup ()
    "Activa valign con fancy bars y fuerza alineación."
    (valign-mode 1)
    (run-with-idle-timer 0.5 nil
      (lambda (buf)
        (when (buffer-live-p buf)
          (with-current-buffer buf
            (valign-region (point-min) (point-max)))))
      (current-buffer)))

  (add-hook 'markdown-mode-hook #'nb/valign-setup t)) ;; t=append, corre al final

;; (valign config movido dentro de after! markdown-mode arriba)

;; Emojis :smile: :wink: etc
(use-package! emojify
  :hook (markdown-mode . emojify-mode)
  :config
  (setq emojify-emoji-styles '(github))
  (setq emojify-display-style 'unicode))
#+end_src

** Tables (valign)
Already configured above in the Beautify Markdown section.

** TOC Org
#+begin_src emacs-lisp
(if (require 'toc-org nil t)
    (progn
      (add-hook 'org-mode-hook #'toc-org-mode)
      ;; enable in markdown, too
      (add-hook 'markdown-mode-hook #'toc-org-mode)
      (after! markdown-mode
        (map! :map markdown-mode-map
              "C-c C-o" #'toc-org-markdown-follow-thing-at-point)))
  (warn "toc-org not found"))

(use-package! toc-org
  :commands toc-org-enable
  :init
  (add-hook 'org-mode-hook #'toc-org-enable))
#+end_src

* AI
** Claude Code
#+begin_src emacs-lisp
(use-package! claudemacs)

(require 'claudemacs)
(define-key prog-mode-map (kbd "C-c C-e") #'claudemacs-transient-menu)
(define-key emacs-lisp-mode-map (kbd "C-c C-e") #'claudemacs-transient-menu)
(define-key text-mode-map (kbd "C-c C-e") #'claudemacs-transient-menu)
(with-eval-after-load 'python
  (define-key python-base-mode-map (kbd "C-c C-e") #'claudemacs-transient))

;; Set a big buffer so we can search our history.
(with-eval-after-load 'eat
  (setq eat-term-scrollback-size 400000))

;; If you want it to pop up as a new buffer. Otherwise, it will use "other buffer."
;; Personally, I use the default "other buffer" style.
(add-to-list 'display-buffer-alist
             '("^\\*claudemacs"
               (display-buffer-in-side-window)
               (side . right)
               (window-width . 0.33)))

;; Turn on autorevert because Claude modifies and saves buffers. Make it a habit to save
;; before asking Claude anything, because it uses the file on disk as its source of truth.
;; (And you don't want to lose edits after it modifies and saves the files.)
(global-auto-revert-mode t)


;;
;; font insanity for Claudemacs
;;
(defun my/setup-custom-font-fallbacks-mac ()
  (interactive)
  "Configure font fallbacks on mac for symbols and emojis.
This will need to be called every time you change your font size,
to load the new symbol and emoji fonts."

  (setq use-default-font-for-symbols nil)

  ;; --- Configure for 'symbol' script ---
  ;; We add fonts one by one. Since we use 'prepend',
  ;; the last one added here will be the first one Emacs tries.
  ;; So, list them in reverse order of your preference.

  ;; Least preferred among this list for symbols (will be at the end of our preferred list)
  (set-fontset-font t 'symbol "Hiragino Sans" nil 'prepend)
  (set-fontset-font t 'symbol "STIX Two Math" nil 'prepend)
  (set-fontset-font t 'symbol "Zapf Dingbats" nil 'prepend)
  (set-fontset-font t 'symbol "Monaco" nil 'prepend)
  (set-fontset-font t 'symbol "Menlo" nil 'prepend)
  ;; Most preferred for symbols -- use your main font here
  (set-fontset-font t 'symbol "JetBrainsMono Nerd Font Mono" nil 'prepend)


  ;; --- Configure for 'emoji' script ---
  ;; Add fonts one by one, in reverse order of preference.

  ;; Least preferred among this list for emojis
  (set-fontset-font t 'emoji "Hiragino Sans" nil 'prepend)
  (set-fontset-font t 'emoji "STIX Two Math" nil 'prepend)
  (set-fontset-font t 'emoji "Zapf Dingbats" nil 'prepend)
  (set-fontset-font t 'emoji "Monaco" nil 'prepend)
  (set-fontset-font t 'emoji "Menlo" nil 'prepend)
  ;; (set-fontset-font t 'emoji "Noto Emoji" nil 'prepend) ;; If you install Noto Emoji
  ;; Most preferred for emojis -- use your main font here
  (set-fontset-font t 'emoji "JetBrainsMono Nerd Font Mono" nil 'prepend))

;; to test if you have a font family installed:
;   (find-font (font-spec :family "Menlo"))

;; Then, add the fonts after your setup is complete:
(add-hook 'emacs-startup-hook
          (lambda ()
            (progn
              (when (string-equal system-type "darwin")
                (my/setup-custom-font-fallbacks-mac)))))
#+end_src

** OpenAI Codex
Coming soon...

** Tree sitter and colors

#+begin_src emacs-lisp
(setq treesit-language-source-alist
      '((javascript . "https://github.com/tree-sitter/tree-sitter-javascript")
        (jsdoc      . "https://github.com/tree-sitter/tree-sitter-jsdoc")
        (html       . "https://github.com/tree-sitter/tree-sitter-html")
        (css        . "https://github.com/tree-sitter/tree-sitter-css")
        (json       . "https://github.com/tree-sitter/tree-sitter-json")
        (ruby       . "https://github.com/tree-sitter/tree-sitter-ruby")))
#+end_src
